version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    user: mongodb
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db
    networks:
      - app-network

# volumes:
#   mongo_data:

networks:
  app-network: