name: Lint
## on: [push, pull_request]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Node.js Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linter
        run: npx jshint@2.12.0 .